baseURL: # https://github.com/phyphox/expdb-generator/
params:
  contact:
    name: II. Lehrstuhl für Physik, RWTH Aachen
    email:
    phone:

defaultContentLanguage: de
defaultContentLanguageInSubdir: true

# all new languages should have a weight >2 as hugo uses the weight to decide which language to use as fallback;
# & it is probable that English & German will get the most support.
# The taxonomies need to be translated in the exact same order as listed here!
languages:
  en:
    taxonomies:
      category: "categories"
      tag: "tags"
      Domain of Physics: "Domains of Physics"
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: The Official Database For Various phyphox Experiment Resources.
    title: phyphox Database Prototype
    weight: 1

  de:
    taxonomies:
      category: "Kategorien"
      tag: "Etiketten"
      Domain of Physics: "Bereiche der Physik"
    permalinks:
      page:
        instructions: /anleitungen/:slug/
      section:
        instructions: /anleitungen/
    disabled: false
    languageCode: de-DE
    languageDirection: ltr
    languageName: Deutsch
    params:
      subtitle: Die offizielle Sammlung von Ressourcen für phyphox-Experimente.
    title: phyphox Datenbank Prototyp
    weight: 2