baseURL: #https://phyphox.org/expdb
params:
  contact:
    name: phyphox-Team, RWTH Aachen
    email: contact@phyphox.org
    phone:
  math: true

defaultContentLanguage: en

# all new languages should have a weight >2 as hugo uses the weight to decide which language to use as fallback;
# & it is probable that English & German will get the most support.
languages:
  en:
    contentDir: content/en

    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: A Database for phyphox Experiment Resources.
    title: phyphox Experiment Database

    weight: 1
  de:
    contentDir: content/de

    disabled: false
    languageCode: de-DE
    languageDirection: ltr
    languageName: Deutsch
    params:
      subtitle: Eine Sammlung von phyphox-Ressourcen.
    title: phyphox Experiment-Datenbank
    weight: 2

# theme: onion

#module:
# imports:
#  - path: github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs

taxonomies:
  category: categories
  tag: tags
  level: levels
  sensor: sensors
  material: materials

ignorefiles: "generated/.*\\.html"

enableEmoji: true
markup:
  goldmark:
    parser:
      attribute:
        block: true
      wrapStandAloneImageWithinParagraph: false
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
        enable: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
