baseURL: #https://phyphox.org/expdb
params:
  contact:
    name: phyphox-Team, RWTH Aachen
    email: contact@phyphox.org
    phone:
  math: true

defaultContentLanguage: en

# all new languages should have a weight >2 as hugo uses the weight to decide which language to use as fallback;
# & it is probable that English & German will get the most support.
languages:
  en:
    contentDir: content/en
    permalinks:
      page:
        instructions: /instructions/:slug/

    taxonomies:
      category: "categories"
      tag: "tags"

    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: A Database for phyphox Experiment Resources.
    title: phyphox Experiment Database

    weight: 1
  de:
    contentDir: content/de

    permalinks:
      categories: "/:section/:slug"
      page:
        instructions: /anleitungen/:slug/
      section:
        instructions: /anleitungen/

    taxonomies:
      category: "Kategorien"
      tag: "Stichwörter"

    disabled: false
    languageCode: de-DE
    languageDirection: ltr
    languageName: Deutsch
    params:
      subtitle: Eine Sammlung von phyphox-Ressourcen.
    title: phyphox Experiment-Datenbank
    weight: 2

# theme: onion

#module:
# imports:
#  - path: github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs

taxonomies:
  category: categories
  tag: tags

enableEmoji: true
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
        enable: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
